<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\db\Expression;

/**
 * LoginForm is the model behind the login form.
 *
 * @property Candidate $candidate
 *
 */
class ClaimForm extends Model
{
    public $claims;
    public $candidate;
    public $sandbox;

    public function __construct($sandbox = false, $candidate = false)
    {
        parent::__construct();
        $this->sandbox = $sandbox;
        $this->candidate = $candidate ? Candidate::findOne(['id' => $candidate]) : Candidate::find()
            ->orderBy(new Expression('rand()'))
            ->one();
    }


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['claims'], 'string'],
            [['claims'], 'required'],
        ];
    }

    public function attributeLabels()
    {
        return ["claims" => "tvrzení"]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if ($this->validate()) {
            $result = [];
            foreach (explode("\n", $this->claims) as $claim_) {
                if (strlen(trim($claim_))) {
                    $claim = new Claim([
                        'sentence_id' => $this->candidate->sentence,
                        'entity' => $this->candidate->entity,
                        'claim' => $claim_,
                        'sandbox' => $this->sandbox,
                        'labelled' => 0,
                        'candidate' => $this->candidate->id,
                        'user' => Yii::$app->user->id
                    ]);
                    if ($claim->save(false)) {
                        $result[] = $claim->id;
                    }
                }
            }
            Yii::$app->session->set('claims', $result);
            return true;
        }
        return false;
    }
}
