<?php

namespace app\models;

use phpDocumentor\Reflection\Types\Parent_;
use Yii;
use yii\behaviors\TimestampBehavior;
use yii\db\ActiveQuery;

/**
 * This is the model class for table "paragraph".
 *
 * @property int $id Identifikátor
 * @property int $rank Pořadí věty ve článku
 * @property string $article ČTK článek
 * @property string $text Text odstavce
 * @property string[] $ners Pojmenované entity
 * @property int|null $candidate_of Uživatel, který zařadil větu do Ú1
 * @property int|null $created_at Datum vzniku
 * @property int|null $updated_at Datum poslední změny
 *
 * @property ClaimKnowledge[] $claimKnowledges
 * @property Evidence[] $evidences
 * @property Label[] $labels
 * @property Article $article0
 * @property User $candidateOf
 * @property ParagraphKnowledge[] $paragraphKnowledges
 */
class Paragraph extends CtkData
{
    private $_before;
    private $_after;

    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'paragraph';
    }

    public static function findByCtkId($id)
    {
        $id = explode("_", $id);
        return self::findOne(['article' => $id[0], 'rank' => $id[1]]);
    }

    public function afterFind()
    {
        if ($this->ners !== null) {
            $this->ners = explode(",", $this->ners);
        }
        return parent::afterFind();
    }

    public function beforeValidate()
    {
        if (is_array($this->ners)) {
            $this->ners = implode(",", $this->ners);
        }
        return parent::beforeValidate();
    }

    public function behaviors()
    {
        return [
            TimestampBehavior::class,
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['rank', 'article', 'text'], 'required'],
            [['rank', 'candidate_of', 'created_at', 'updated_at'], 'integer'],
            [['text', 'ners'], 'string'],
            [['article'], 'string', 'max' => 64],
            [['article'], 'exist', 'skipOnError' => true, 'targetClass' => Article::class, 'targetAttribute' => ['article' => 'id']],
            [['candidate_of'], 'exist', 'skipOnError' => true, 'targetClass' => User::class, 'targetAttribute' => ['candidate_of' => 'id']],
        ];
    }

    public function beforeSave($insert)
    {
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id' => 'Identifikátor',
            'rank' => 'Pořadí věty ve článku',
            'article' => 'ČTK článek',
            'text' => 'Text odstavce',
            'ners' => 'Pojmenované entity',
            'candidate_of' => 'Uživatel, který zařadil větu do Ú1',
            'created_at' => 'Datum vzniku',
            'updated_at' => 'Datum poslední změny',
        ];
    }

    /**
     * Gets query for [[ClaimKnowledges]].
     *
     * @return ActiveQuery
     */
    public function getClaimKnowledges()
    {
        return $this->hasMany(ClaimKnowledge::class, ['knowledge' => 'id']);
    }

    /**
     * Gets query for [[Evidences]].
     *
     * @return ActiveQuery
     */
    public function getEvidences()
    {
        return $this->hasMany(Evidence::class, ['paragraph' => 'id']);
    }

    /**
     * Gets query for [[Labels]].
     *
     * @return ActiveQuery
     */
    public function getLabels()
    {
        return $this->hasMany(Label::class, ['id' => 'label'])->viaTable('evidence', ['paragraph' => 'id']);
    }

    /**
     * Gets query for [[Article0]].
     *
     * @return ActiveQuery
     */
    public function getArticle0()
    {
        return $this->hasOne(Article::class, ['id' => 'article']);
    }

    /**
     * Gets query for [[CandidateOf]].
     *
     * @return ActiveQuery
     */
    public function getCandidateOf()
    {
        return $this->hasOne(User::class, ['id' => 'candidate_of']);
    }

    /**
     * Gets query for [[ParagraphKnowledges]].
     *
     * @return ActiveQuery
     */
    public function getParagraphKnowledges()
    {
        return $this->hasMany(ParagraphKnowledge::class, ['paragraph' => 'id']);
    }

    public function getKnowledge()
    {
        return $this->hasMany(Paragraph::class, ['id' => 'knowledge'])
            ->viaTable('paragraph_knowledge', ['paragraph' => 'id']);
    }

    public function getCtkId()
    {
        return $this->article . '_' . $this->rank;
    }
}
