<?php

namespace app\models;

use Yii;
use yii\base\Model;
use yii\db\Expression;

/**
 * LoginForm is the model behind the login form.
 *
 * @property Tweet $tweet
 *
 */
class TwitterForm extends Model
{
    public $claims;
    public $tweet;
    public $sandbox;

    public function __construct($sandbox = false, $tweet = false)
    {
        parent::__construct();
        $this->sandbox = $sandbox;
        $traversed = [];
        if (!$tweet) {
            do {
                $this->tweet = (TweetKnowledge::find()
                    ->orderBy(new \yii\db\Expression('rand()'))
                    ->one())->tweet0;
                $traversed[] = $this->tweet;
            } while (Claim::find()->where(['tweet' => $this->tweet->id, 'user' => Yii::$app->user->id])->exists());
        } else {
            $this->tweet = Tweet::findOne(['id' => $tweet]);
        }
    }


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            // username and password are both required
            [['claims'], 'string'],
            [['claims'], 'required'],
        ];
    }

    public function attributeLabels()
    {
        return ["claims" => "tvrzení"]; // TODO: Change the autogenerated stub
    }

    public function save()
    {
        if ($this->validate()) {
            $result = [];
            foreach (array_reverse(explode("\n", $this->claims)) as $claim_) {
                if (strlen(trim($claim_))) {
                    $claim = new Claim([
                        'tweet' => $this->tweet->id,
                        'claim' => $claim_,
                        'sandbox' => $this->sandbox,
                        'labelled' => 0,
                        'user' => Yii::$app->user->id
                    ]);
                    if ($claim->save(false)) {
                        $result[] = $claim->id;
                    }
                }
            }
            return true;
        }
        return false;
    }
}
